spring.application.name=group
spring.session.jdbc.initialize-schema=always

server.port=${PORT:8080}
server.forward-headers-strategy=framework

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#spring.datasource.url=jdbc:postgresql://dpg-d8qa35vlk1mc739njgdg-a.oregon-postgres.render.com/group_db
#spring.datasource.username=as2_database_user
#spring.datasource.password=XmXb09Afhmvzx9CFVhmzAqqMAgTAE4Nn

#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/group_db}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432}
#spring.datasource.url=jdbc:postgresql://localhost:5432/group_db
spring.datasource.username=${DB_USR:postgres}
spring.datasource.password=${DB_PWD:postgres}


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
