spring.application.name=group
spring.session.jdbc.initialize-schema=always

server.port=${PORT:8080}
server.forward-headers-strategy=framework

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# spring.datasource.url=jdbc:postgresql://dpg-d9f7o5j7uimc73ar8h80-a.oregon-postgres.render.com/shindb
# spring.datasource.username=shindb_user
# spring.datasource.password=lN9pJ96vUBUpJsUJ9EI7vdMQloFj9h5K
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/}
spring.datasource.username=${DB_USR:postgres}
spring.datasource.password=${DB_PWD:postgres}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
